name: webTestDart
description: A sample web application
dependencies:
  angular: ">=0.10.0 <0.12.0"
  browser: any
  js: any
  shadow_dom: any
  http: ">=0.11.1 <0.12.0"
  http_server: any
  route: ">=0.4.6 <0.5.0"
  route_hierarchical: '>=0.4.18 <0.5.0'
dev_dependencies:
  unittest: any
transformers:
- angular