name: webTestDart
description: A sample web application
dependencies:
  angular: ">=0.10.0 <0.12.0"
  browser: any
  exportable: ">=0.1.0 <0.2.0"
  js: any
  json_object: any
  shadow_dom: any
  route: ">=0.4.6 <0.5.0"
  route_hierarchical: '>=0.4.18 <0.5.0'
dev_dependencies:
  unittest: any
transformers:
- angular